all:
  stylesheets:   [-main, -admin, /sfDoctrinePlugin/css/global.css, /sfDoctrinePlugin/css/default.css, main, admin, /mediatorPlugin/css/cleverMediaLibrary]
  javascripts:   [/mediatorPlugin/js/jquery.min.js, /mediatorPlugin/js/jquery.livequery.js]

chooseImageSuccess:
  layout:        facebox
  stylesheets:   [/mediatorPlugin/css/cleverMediaLibrary]

editSuccess:
  stylesheets:   [/mediatorPlugin/css/jquery.Jcrop.css, /mediatorPlugin/css/cleverMediaLibrary]
  javascripts:   [/mediatorPlugin/js/jquery.Jcrop.js]

listSuccess:
  stylesheets:   [/mediatorPlugin/css/cleverMediaLibrary]
  javascripts:   [/mediatorPlugin/js/cleverMediaLibrary, /mediatorPlugin/js/jquery.pageslider.js]

searchSuccess:
  stylesheets:   [/mediatorPlugin/css/cleverMediaLibrary]
  javascripts:   [/mediatorPlugin/js/cleverMediaLibrary]

viewSuccess:
  stylesheets:   [/sfFormExtraPlugin/css/jquery.autocompleter.css, /mediatorPlugin/css/cleverMediaLibrary]
  javascripts:   [/mediatorPlugin/js/jquery.pageslider.js]
