app:
  mediatorMediaLibraryPlugin:
    default_adapters:
      mediatorMediaImageHandler:    mediatorMediaImageImageMagickAdapter
    fs:                localdisk
    media_root:        /
    use_nested_set:    false
    thumbnail_types:
      - jpg
      - png
      - gif
    metadata_exif:
      - Artist
      - Copyright
      - DateTimeOriginal
      - ExposureTime
      - FocalLength
      - FocalLengthIn35mmFilm
      - ISOSpeedRatings
      - Make
      - Model
    directories:
      original:
        directory: original
      large:
        directory: large
        width: 500
        height: 500
        overwrite: true
      medium:
        directory: medium
        width: 300
        height: 300
        overwrite: true
      small:
        directory: small
        width: 100
        height: 100
        overwrite: true
