all:
  mediatorMediaLibraryPlugin:
    default_adapters:
      mediatorMediaImageHandler:    mediatorMediaImageImageMagickAdapter
    fs:                             localdisk
    upload_simultaneaous:           3
    media_root:                     /media/
    media_types:
      images:                     "*.jpg;*.jpeg;*.png;*.gif;*.bmp"
      sound:                      "*.aac;*.wma;*.mp3;*.wav"
      video:                      "*.mpeg;*.mp4;*.m4v;*.mov;*.flv;*.avi;*.mpg"
    use_nested_set:                 false
    thumbnail_types:
      - jpg
      - png
      - gif
    metadata_exif:
      - Artist
      - Copyright
      - DateTimeOriginal
      - ExposureTime
      - FocalLength
      - FocalLengthIn35mmFilm
      - ISOSpeedRatings
      - Make
      - Model
    directories:
      # this directory is used to store the original media
      original:
        directory:                original
      large:
        directory:                large
        width:                    500
        height:                   500
        overwrite:                true
      medium:
        directory:                medium
        width:                    300
        height:                   300
        overwrite:                true
      small:
        directory:                small
        width:                    100
        height:                   100
        overwrite:                true