all:
  stylesheets:   [/sfDoctrinePlugin/css/global.css: { position: first }, /sfDoctrinePlugin/css/default.css: { position: first }, /mediatorMediaLibraryPlugin/css/facebox, /mediatorMediaLibraryPlugin/css/mediatorMediaLibrary]
  javascripts:   [/mediatorMediaLibraryPlugin/js/facebox.js]

chooseSuccess:
  has_layout:    false
  javascripts:   [/mediatorMediaLibraryPlugin/js/jquery.form.js, /mediatorMediaLibraryPlugin/js/jquery.autoSuggest.js]
  stylesheets:   [/mediatorMediaLibraryPlugin/css/autoSuggest.css]

describeSuccess:
  javascripts:   [/mediatorMediaLibraryPlugin/js/jquery.autoSuggest.js]
  stylesheets:   [/mediatorMediaLibraryPlugin/css/autoSuggest.css]

editSuccess:
  stylesheets:   [/mediatorMediaLibraryPlugin/css/jquery.Jcrop.css]
  javascripts:   [/mediatorMediaLibraryPlugin/js/jquery.Jcrop.js]

listSuccess:
  javascripts:   [/mediatorMediaLibraryPlugin/js/jquery.pageslider.js]

viewSuccess:
  stylesheets:   [/sfFormExtraPlugin/css/jquery.autocompleter.css, /mediatorMediaLibraryPlugin/css/video-js.css]
  javascripts:   [/mediatorMediaLibraryPlugin/js/jquery.pageslider.js, /mediatorMediaLibraryPlugin/js/video.js]
